### ISSUE TITLE
Cannot find module './lib/words'

### ISSUE THREAD

**Issue by JulianKingman** [cmroanirgo/pl-copyfind#1]
I'm not sure why, it looks OK, but it's this error is preventing the startup of PS.

```
W20170610-11:59:20.456(-4)? (STDERR) /Users/Julian/.meteor/packages/meteor-tool/.1.4.4_2.1ttvtuv++os.osx.x86_64+web.browser+web.cordova
/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170610-11:59:20.457(-4)? (STDERR)                                            throw(ex);
W20170610-11:59:20.457(-4)? (STDERR)                                            ^
W20170610-11:59:20.458(-4)? (STDERR)
W20170610-11:59:20.459(-4)? (STDERR) Error: Cannot find module './lib/words'
W20170610-11:59:20.460(-4)? (STDERR)     at require (packages/modules-runtime.js:123:19)
W20170610-11:59:20.461(-4)? (STDERR)     at meteorInstall.node_modules.pl-copyfind.index.js (packages/modules.js:452:15)
W20170610-11:59:20.461(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170610-11:59:20.462(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170610-11:59:20.462(-4)? (STDERR)     at Module.Mp.importSync (/Users/Julian/.meteor/packages/modules/.0.8.2.qbnbx9++os+web.browser+
web.cordova/npm/node_modules/reify/lib/runtime.js:82:24)
W20170610-11:59:20.462(-4)? (STDERR)     at meteorInstall.server.checkPlCopyfind.js (server/checkPlCopyfind.js:1:21)
W20170610-11:59:20.463(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170610-11:59:20.463(-4)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170610-11:59:20.463(-4)? (STDERR)     at /Users/Julian/OneDrive/Meteor/ps/.meteor/local/build/programs/server/app/app
.js:2477:1
W20170610-11:59:20.464(-4)? (STDERR)     at /Users/Julian/OneDrive/Meteor/ps/.meteor/local/build/programs/server/boot.js
:303:34
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by cmroanirgo** [comment]
Note sure why that is, I've used this package in quite a few places, using `npm install pl-copyfind`...

Any chance the meteor packager is doing something strange? I had a look at Meteor's [Using npm Packages](https://guide.meteor.com/using-npm-packages.html) and admittedly, got a little bewildered at the various meteor-isms.

If you have a look at the source tree here, you'll see the `lib` folder with two files in it (`words.js` and `textreader.js`). You should have those in your meteor install folders.

I also came across this fault: https://github.com/meteor/meteor/issues/7215#issuecomment-226534952

> On initial load, app is fine, then the first time the browser hot reloads, we get these import errors.

[also](https://github.com/meteor/meteor/issues/7215#issuecomment-226559754):

> In the meantime, here's a workaround for the second problem:
> import "expect/node_modules/has";

So, perhaps manually doing this in your code?:

```
import "pl-copyfind/lib/words"
import "pl-copyfind/lib/textreader"
```

**Comment by cmroanirgo** [comment]
It seems this is a 'meteorism', so closing it until more info arrives.

**Comment by JulianKingman** [comment]
Anyway, it's working now...
